# Получить токен можно тут: https://goo.gl/GYbXTD
# Плагин от TesLex Team
# Наш сайт: teslex.tech
# Мы в Вконтакте: vk.com/teslex.team

# Токен
token: besttoken
# Айди того, кому отправлять сообщения о новых репотрах
id: 380494874
# Сообщение:
# {PLAYER} - ник игрока
# {TEXT} - текст сообщения игрока
# <br> - новая строка
msg: "Новое оповещение!<br>Отправлено игроком: {PLAYER}<br>Текст: {TEXT}"